Repository schrodinger/infra-tester, pull requests merged in 2023-09, with the labels that each got.

#20 Renamed infra-tester config file
  docs/docs/configuration.md
  docs/docs/extending_infra_tester.md
  docs/docs/writing_tests.md
  example/.infra-tester-config.yaml
  src/main_test.go
Labels: documentation, enhancement

#23 Add `go install` compatibility
  .github/workflows/build_release_binaries.yml
  .github/workflows/run_test.yaml
  assertions/apply_assertions.go
  assertions/assertions.go
  assertions/custom_assertions.go
  assertions/decoder.go
  assertions/plan_assertions.go
  assertions/utils.go
  docs/docs/extending_infra_tester.md
  docs/docs/index.md
  docs/docs/test_output.md
  docs/docs/writing_tests.md
  go.mod
  go.sum
  main.go
  plugins/plugin_manager.go
  plugins/plugin_result.go
  plugins/plugin_runner.go
  plugins/plugins.go
  python-plugins/LICENSE
  python-plugins/pyproject.toml
  python-plugins/setup.py
  python-plugins/src/infra_tester_plugins/__init__.py
  python-plugins/src/infra_tester_plugins/assertion.py
  python-plugins/src/infra_tester_plugins/cli.py
  python-plugins/src/infra_tester_plugins/result.py
  schema.go
  src/go.mod
  utils/cmd/command_result.go
  utils/cmd/command_runner.go
  utils/json.go
  validation.go
Labels: enhancement

#24 Update install section in docs
  docs/docs/index.md
Labels: documentation
